# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceprovider_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('service_map_id', models.IntegerField()),
                ('service_request_id', models.IntegerField()),
                ('booked_time', models.DateTimeField(auto_now_add=True)),
                ('service_map_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohservicemap', to='onelinkapp.ServiceMap')),
            ],
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_map_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_map_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onelinkapp.ServiceMap'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='service_request_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohservicerequest', to='onelinkapp.ServiceRequest'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='serviceprovider_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohproviderdetail', to='onelinkapp.UserDetail'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='user_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohuserdetail', to='onelinkapp.UserDetail'),
        ),
    ]
