# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0002_auto_20170607_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmap',
            name='item_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
