# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0003_auto_20170607_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmap',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='itemmap',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='itemmap',
            name='item_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
