# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0005_auto_20170612_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemap',
            name='areapincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
