# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0006_auto_20170613_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotification',
            name='request_type',
            field=models.CharField(blank=True, default='product', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicenotification',
            name='request_type',
            field=models.CharField(blank=True, default='service', max_length=10, null=True),
        ),
    ]
