# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0007_auto_20170613_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorderhistory',
            name='confirmation_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='confirmation_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='areapincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='areapincode',
            field=models.CharField(max_length=10),
        ),
    ]
