# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0008_auto_20170613_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('sending_time', models.DateTimeField(auto_now_add=True)),
                ('message_text', models.TextField()),
                ('request_type', models.CharField(max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('itemrequest_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgsservicerequest', to='onelinkapp.ItemRequest')),
                ('receiver_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgreceiver', to='onelinkapp.UserDetail')),
                ('sender_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgsender', to='onelinkapp.UserDetail')),
                ('servicerequest_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgsservicerequest', to='onelinkapp.ServiceRequest')),
            ],
        ),
        migrations.AlterField(
            model_name='itemnotification',
            name='request_type',
            field=models.CharField(blank=True, default='PRODUCT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicenotification',
            name='request_type',
            field=models.CharField(blank=True, default='SERVICE', max_length=10, null=True),
        ),
    ]
