# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0023_auto_20170704_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmap',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='servicemap',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
