# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0024_auto_20170710_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmap',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicemap',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
