# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0026_requestmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='product_detail_ch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_name_ch',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='service_detail_ch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='service_name_ch',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='service_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
